modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="lonsdaleite_mod"
version="1.0.0"
displayName="Lonsdaleite Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Κωνσταντίνος Τσότας, MCreator"

[[dependencies.lonsdaleite_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




